services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: electron-platform-back-ts
    container_name: electron-platform-back-ts
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: electron-platform-front
    container_name: electron-platform-front
    working_dir: /front
    volumes:
      - ./front:/front
    ports:
      - "8080:8080"
